### ISSUE TITLE
FastAPI and Pydantic - Relationships Not Working

### ISSUE THREAD

**Issue by Chunkford** [tiangolo/sqlmodel#37]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from typing import List, Optional

from fastapi import Depends, FastAPI, HTTPException, Query
from sqlmodel import Field, Relationship, Session, SQLModel, create_engine, select


class TeamBase(SQLModel):
    name: str
    headquarters: str


class Team(TeamBase, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)

    heroes: List["Hero"] = Relationship(back_populates="team")


class TeamCreate(TeamBase):
    pass


class TeamRead(TeamBase):
    id: int


class TeamUpdate(SQLModel):
    id: Optional[int] = None
    name: Optional[str] = None
    headquarters: Optional[str] = None


class HeroBase(SQLModel):
    name: str
    secret_name: str
    age: Optional[int] = None

    team_id: Optional[int] = Field(default=None, foreign_key="team.id")


class Hero(HeroBase, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)

    team: Optional[Team] = Relationship(back_populates="heroes")


class HeroRead(HeroBase):
    id: int


class HeroCreate(HeroBase):
    pass


class HeroUpdate(SQLModel):
    name: Optional[str] = None
    secret_name: Optional[str] = None
    age: Optional[int] = None
    team_id: Optional[int] = None


class HeroReadWithTeam(HeroRead):
    team: Optional[TeamRead] = None


class TeamReadWithHeroes(TeamRead):
    heroes: List[HeroRead] = []


sqlite_file_name = "database.db"
sqlite_url = f"sqlite:///{sqlite_file_name}"

connect_args = {"check_same_thread": False}
engine = create_engine(sqlite_url, echo=True, connect_args=connect_args)


def create_db_and_tables():
    SQLModel.metadata.create_all(engine)


def get_session():
    with Session(engine) as session:
        yield session


app = FastAPI()


@app.on_event("startup")
def on_startup():
    create_db_and_tables()


@app.post("/heroes/", response_model=HeroRead)
def create_hero(*, session: Session = Depends(get_session), hero: HeroCreate):
    db_hero = Hero.from_orm(hero)
    session.add(db_hero)
    session.commit()
    session.refresh(db_hero)
    return db_hero


@app.get("/heroes/", response_model=List[HeroRead])
def read_heroes(
    *,
    session: Session = Depends(get_session),
    offset: int = 0,
    limit: int = Query(default=100, lte=100),
):
    heroes = session.exec(select(Hero).offset(offset).limit(limit)).all()
    return heroes


@app.get("/heroes/{hero_id}", response_model=HeroReadWithTeam)
def read_hero(*, session: Session = Depends(get_session), hero_id: int):
    hero = session.get(Hero, hero_id)
    if not hero:
        raise HTTPException(status_code=404, detail="Hero not found")
    return hero


@app.patch("/heroes/{hero_id}", response_model=HeroRead)
def update_hero(
    *, session: Session = Depends(get_session), hero_id: int, hero: HeroUpdate
):
    db_hero = session.get(Hero, hero_id)
    if not db_hero:
        raise HTTPException(status_code=404, detail="Hero not found")
    hero_data = hero.dict(exclude_unset=True)
    for key, value in hero_data.items():
        setattr(db_hero, key, value)
    session.add(db_hero)
    session.commit()
    session.refresh(db_hero)
    return db_hero


@app.delete("/heroes/{hero_id}")
def delete_hero(*, session: Session = Depends(get_session), hero_id: int):

    hero = session.get(Hero, hero_id)
    if not hero:
        raise HTTPException(status_code=404, detail="Hero not found")
    session.delete(hero)
    session.commit()
    return {"ok": True}


@app.post("/teams/", response_model=TeamRead)
def create_team(*, session: Session = Depends(get_session), team: TeamCreate):
    db_team = Team.from_orm(team)
    session.add(db_team)
    session.commit()
    session.refresh(db_team)
    return db_team


@app.get("/teams/", response_model=List[TeamRead])
def read_teams(
    *,
    session: Session = Depends(get_session),
    offset: int = 0,
    limit: int = Query(default=100, lte=100),
):
    teams = session.exec(select(Team).offset(offset).limit(limit)).all()
    return teams


@app.get("/teams/{team_id}", response_model=TeamReadWithHeroes)
def read_team(*, team_id: int, session: Session = Depends(get_session)):
    team = session.get(Team, team_id)
    if not team:
        raise HTTPException(status_code=404, detail="Team not found")
    return team


@app.patch("/teams/{team_id}", response_model=TeamRead)
def update_team(
    *,
    session: Session = Depends(get_session),
    team_id: int,
    team: TeamUpdate,
):
    db_team = session.get(Team, team_id)
    if not db_team:
        raise HTTPException(status_code=404, detail="Team not found")
    team_data = team.dict(exclude_unset=True)
    for key, value in team_data.items():
        setattr(db_team, key, value)
    session.add(db_team)
    session.commit()
    session.refresh(db_team)
    return db_team


@app.delete("/teams/{team_id}")
def delete_team(*, session: Session = Depends(get_session), team_id: int):
    team = session.get(Team, team_id)
    if not team:
        raise HTTPException(status_code=404, detail="Team not found")
    session.delete(team)
    session.commit()
    return {"ok": True}
```

### Description

Is realationships working for anyone?
I either get null or an empty list.

OK, so, I've copied the last full file preview at the - https://sqlmodel.tiangolo.com/tutorial/fastapi/relationships/
Run it and it creates the Db and the foreign key
Then I've insert the data into the Db.

Checking the docs UI everything looks great
<img width="1368" alt="Screenshot 2021-08-26 at 23 33 55" src="https://user-images.githubusercontent.com/11464425/131044799-26f45765-95bf-4528-8353-4277dcfceb3e.png">

But when I do a request for a hero, `team` is `null`
<img width="1400" alt="Screenshot 2021-08-26 at 23 36 39" src="https://user-images.githubusercontent.com/11464425/131044990-e773fe1f-3b3a-48e4-9204-74ce0b14718c.png">

Really not sure what going on, especially when all I have just is copied the code example with no changes?

### Operating System

Linux

### SQLModel Version

0.0.4

### Python Version

3.8.2

**Comment by alucarddelta** [comment]
> OK, worked out what it was.
> I was using `fastapi==0.68.0`
> There's a newer version `fastapi==0.68.1` that added support for `read_with_orm_mode` - https://github.com/tiangolo/fastapi/releases/tag/0.68.1
> 
> @alucarddelta update fastapi `pip install fastapi -U` and it should resolve the issue

This worked @Chunkford, I have submitted a pull request to change the pip requirement for the project to be 0.68.1 as it was set to 0.68.0.

**Comment by lobotmcj** [comment]
🤦‍♂️ I lost so many hours on this -- thank you for the version update recommendation and MR!

**Comment by rickerp** [comment]
Still having the same issue, here is my case:
```
fastapi==0.70.0
sqlmodel==0.0.4
```
```py
class Professional(Base, table=True):
    permissions: ProfessionalPermissions = Field(ProfessionalPermissions.NONE, nullable=False,
                                                 sa_column_kwargs={'server_default': text('0')})
    store_id: UUID = Field(foreign_key="store.id", primary_key=True)
    store: List['Store'] = Relationship(back_populates="professionals")
```
```py
class Store(Base, table=True):
    id: UUID = UUIDField(primary_key=True)
    # ORM Relationships
    professionals: List['Professional'] = Relationship(back_populates="store")
```
```py
@router.get("", response_model=List[Store])
def list_stores(
        limit: int = 100,
        offset: int = 0,
        crud: CRUDController = Depends(get_crud),
        _: User = Depends(get_current_user),
):
    r = crud.store.list(limit, offset)
    print(r[0].professionals)
    return r
```
What I get in the request response
```json
[
  {
    "created_at": "2021-12-10T15:45:05.382071",
    "id": "7847365b-bae3-467e-9efa-e6b6f09c5e80",
    "phone_number": "+351210000001",
    "email": "store1@scedle.com",
    "updated_at": "2021-12-10T15:45:05.382071",
    "name": "Store 1"
  }, 
  ...
]
```
What I get in the terminal with the `print(r[0].professionals)`
```
[Professional(permissions=65535, store_id=UUID('7847365b-bae3-467e-9efa-e6b6f09c5e80'), created_at=datetime.datetime(2021, 12, 10, 15, 45, 5, 382000), updated_at=datetime.datetime(2021, 12, 10, 15, 45, 5, 382000), user_id=UUID('b4883904-6d7b-4ce
d-93e9-c6d1a3c5cdb4'))]
```

**Comment by jonra1993** [comment]
I had the same problem but using an async engine. I solve it using **selectinload** as suggested here https://github.com/tiangolo/sqlmodel/issues/74

response = await db_session.exec(select(self.model).where(self.model.id == id).options(selectinload('*')))

**Comment by alexfromapex** [comment]
My issue with this was that my Pydantic models for my endpoints (response models) weren't lining up with my SQLAlchemy models.  There's really good info [here](https://sqlmodel.tiangolo.com/tutorial/fastapi/relationships/).

**Comment by Gauth27** [comment]
This issue exists in 0.78.0 version for me. Anyone else facing the same in the latest version? Please help.

**Comment by pesc** [comment]
> This issue exists in 0.78.0 version for me. Anyone else facing the same in the latest version? Please help.

Have a look at: #315

Pinning `SQLAlchemy = ">=1.4.17,<=1.4.35"` helped me!

**Comment by fkeil** [comment]
I had the same error using sqlmodel with SQLAlchemy 1.4.40... `user: "User" = Relationship(back_populates="person")` \\\  `person: Person = Relationship(back_populates="user")`
During the creation process, if User need to reference `person_id = int = Field(foreign_key="person.id")`  it will fail. Even if I commit the changes and refresh the instance, the callback will be always null.

**How to reproduce:** Use sqlmodel=0.0.6 with SQLAlchemy=**1.4.40**
Using SQLAlchemy 1.4.35 works flawlessly

**Comment by tiangolo** [comment]
Thanks for the discussion everyone! Yep, for the original problem, you should use the latest FastAPI, at least `0.68.1`.

For the other issues, it was indeed reported in https://github.com/tiangolo/sqlmodel/issues/315, it was solved in https://github.com/tiangolo/sqlmodel/pull/322, and it will be available in the next version, released in the next hours, SQLModel `0.0.7`. :rocket:

**Comment by nick-catalist** [comment]
We are still seeing this error, very similarly to rickerp. We have a model with a one to many relationship (e.g. Team to Heroes). In our route, we can print the Team object, and it has Heroes populated. However, when we get the response from the router, it is totally missing. We are on FastAPI version 0.85.1 and SQLModel version 0.0.8.

e.g.

```
@router.get("/{team_id}/", response_model=Team)
async def get_team(
    team_id: uuid.UUID,
    authed_user: AuthedUser = Depends(get_authed_user),
    db: Session = Depends(get_db),
) -> sql.Project:
    team = TeamOperator(db).get_team(team_id)
    print("TEAM:", team)
    print("HEROES:", team.heroes)
    return team
```

The prints have all the data populated. But in receiving this response, the data for heroes is totally missing. Our team model looks like this:

```
class Team(SQLModel, table=True):
    __tablename__ = 'team'

    id: uuid.UUID = Field(sa_column=Column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        nullable=False,
        unique=True,
    ))
    name: str = Field(sa_column=Column(String, nullable=False))
    heroes: List["Hero"] = Relationship(back_populates="team", sa_relationship_kwargs={
        "cascade": "all, delete-orphan"
    })
```

**Comment by nick-catalist** [comment]
It seems that at the root if the issue is the fact that in FastAPI's encoder call, it's calling `.dict()` on the object, which does not include the `heroes` attribute.  https://github.com/tiangolo/fastapi/blob/0.85.1/fastapi/encoders.py#L56

**Comment by JBorrow** [comment]
@nick-catalist, did you have a solution to this? I am also struggling with this. Even when using `.options(subqueryload(...))` my relationship objects are not being returned from the FastAPI endpoint.

**Comment by tonjo** [comment]
There is no need to do subqueryload, if you properly define "out models" and configure `response_model` in your routes.
It is well explained on site.
The encoder does not know how to render a Relationship field, but it knows how to render a list.
So if you have a 1 to many Relationship, in the response_model you have to define a new model with the very same field but defined of type `list`.

**Comment by nick-catalist** [comment]
@JBorrow @tonjo .. right, thank you tonjo for jogging my memory on this as well.

All you need to do is define a separate response model and redefine the relationship field as a list instead. E.G. you'd want a set up like this:

```python
class TeamBase(SQLModel):
    name: str = Field(sa_column=Column(String, nullable=False))

class Team(TeamBase, table=True):
    __tablename__ = 'team'

    id: uuid.UUID = Field(sa_column=Column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        nullable=False,
        unique=True,
    ))
    heroes: list["Hero"] = Relationship(back_populates="team", sa_relationship_kwargs={
        "cascade": "all, delete-orphan"
    })

class TeamResponse(TeamBase, table=True):
    heroes: list["Hero"]
```

Like tonjo said, Pydantic doesn't know how to render a relationship, but it does know how to render a plain list. Additionally, it will coerce your returned value into whatever you have defined as your `response_model` (you can also just make it the output of the router function via `-> TeamResponse` rather than explicitly passing in `response_model` to the router decorator). So if you return a Team object as a TeamResponse object, it will properly populate the `heroes` field.

See more info at https://sqlmodel.tiangolo.com/tutorial/fastapi/relationships/#models-with-relationships

**Comment by JBorrow** [comment]
Ah fantastic, thank you both for your quick reply! This makes sense, though it does feel like a bit of an antipattern (`heroes` is declared to SQLModel as being of type `list[Hero]`) all along.

**Comment by JBorrow** [comment]
Also, @nick-catalist, I presume you want `table=False` for `TeamResponse`

**Comment by nick-catalist** [comment]
Yes, that was a typo, fixed :)

**Comment by realByg** [comment]
instead of creating a new `response_model`, i tried messing with `pydantic` 's `model_serializer` aand came up with this
```python
class Team(SQLModel, table=True):
	id: str = Field(default_factory=uuid, primary_key=True)
	heroes: list['Hero'] | None = Relationship(back_populates='team')

	@model_serializer
	def model_serializer(self):
		data = {
			'heroes': self.heroes,
		}
		for key in self.model_fields.keys():
			data[key] = getattr(self, key)
		return data
```
